### ISSUE TITLE
Implement command line parser

### ISSUE THREAD

**Issue by Hrily** [Hrily/FileGopherServer#1]
Implement a command line parser with following options:
+ `-d <directory>` or `--directory <directory>` : the directory to serve (default to current directory)
+ `-p <port>` or `--port <port>` : the port to serve on (default to 70)
+ `-h` or `--hidden` : show hidden files if specified

**Comment by skprabhanjan** [comment]
Will using boost libraries be okay ?
Here is an example (https://theboostcpplibraries.com/boost.program_options)

**Comment by Hrily** [comment]
@skprabhanjan 
That would be great :+1:
